### ISSUE TITLE
Worker management

### ISSUE THREAD

**Issue by tpellegatta** [vpg/disturb#45]
- Scalability
- Add live worker
- Init worker (shell script?)
- Failover

**Comment by jrmbrgs** [comment]
keepalive could be handle by pm2 as we use it to keep alive nodejs daemon http://pm2.keymetrics.io

**Comment by jrmbrgs** [comment]
lock file management is not enough because of the distributed arch. e.g. the manager must be run only once for the whole cluster, maybe a lock management has to be set globally (els?)
